# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DataProvider": "01_data_provider.ipynb",
         "get_efficiently": "01_data_provider.ipynb",
         "DataProvider.store_interim": "01_data_provider.ipynb",
         "DataProvider.load_interim": "01_data_provider.ipynb",
         "DataProvider.get_phone_codebook": "01_data_provider.ipynb",
         "DataProvider.determine_phone_b07": "01_data_provider.ipynb",
         "DataProvider.check_participant_id": "01_data_provider.ipynb",
         "DataProvider.test_check_participant_id": "01_data_provider.ipynb",
         "DataProvider.set_dtypes": "01_data_provider.ipynb",
         "DataProvider.get_phone_data": "01_data_provider.ipynb",
         "DataProvider.get_ba_codebook": "01_data_provider.ipynb",
         "DataProvider.get_ba_data": "01_data_provider.ipynb",
         "DataProvider.get_duplicate_mov_ids": "01_data_provider.ipynb",
         "DataProvider.get_mov_data": "01_data_provider.ipynb",
         "DataProvider.get_alcohol_per_drink": "01_data_provider.ipynb",
         "DataProvider.get_two_day_data": "01_data_provider.ipynb",
         "GBEProvider": "02_gbe.data_provider.ipynb",
         "GBEProvider.get_gbe_from_movisense": "02_gbe.data_provider.ipynb",
         "GBEProvider.define_initial_dataset": "02_gbe.data_provider.ipynb",
         "GBEProvider.define_baseline_sessions": "02_gbe.data_provider.ipynb",
         "GBEProvider.find_gbe_game_starting_time": "02_gbe.data_provider.ipynb",
         "GBEProvider.check_time_between_sessions": "02_gbe.data_provider.ipynb",
         "GBEProvider.get_gbe_data": "02_gbe.data_provider.ipynb",
         "GBEProvider.get_initial_baseline": "02_gbe.data_provider.ipynb",
         "GBEProvider.get_replication_baseline": "02_gbe.data_provider.ipynb",
         "GBEProvider.decode_gbe_string": "02_gbe.data_provider.ipynb",
         "GBEProvider.decode_gbe_strings": "02_gbe.data_provider.ipynb",
         "WMDataProvider": "03_gbe.wm.data_provider.ipynb",
         "WMDataProvider.decode_wm_strings": "03_gbe.wm.data_provider.ipynb",
         "WMDataProvider.get_wm_trial_types": "03_gbe.wm.data_provider.ipynb",
         "WMDataProvider.add_trial_types": "03_gbe.wm.data_provider.ipynb",
         "WMDataProvider.get_wm_data": "03_gbe.wm.data_provider.ipynb",
         "WMDataProvider.filter_old_app_sessions": "03_gbe.wm.data_provider.ipynb",
         "WMDataProvider.filter_level_two_failures": "03_gbe.wm.data_provider.ipynb"}

modules = ["data_provider.py",
           "gbe/data_provider.py",
           "gbe/wm/data_provider.py",
           "gbe/wm/scoring.py"]

doc_url = "https://hgzech.github.io/trr265/"

git_url = "https://github.com/hgzech/trr265/tree/master/"

def custom_doc_links(name): return None
