# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://hgzech.github.io/trr265/"

git_url = "https://github.com/hgzech/trr265/tree/{branch}/"

def custom_doc_links(name): return None
