package:
  name: trr265
  version: 0.0.5
source:
  sha256: d343f71013e50c4e62c542a4fbe9eb46cb79b1ee448ace858ddf5c6ac6910f6d
  url: https://files.pythonhosted.org/packages/3c/d7/4534c7bebaa765c718084c3cc06486f6374df2155d9d2817557f6d0e2077/trr265-0.0.5.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: The TRR 265 analysis pipeline.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - biur
  - fastcore
  run:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - biur
  - fastcore
test:
  imports:
  - trr265
