package:
  name: trr265
  version: 0.0.6
source:
  sha256: 98590226221fc3808043acb8f7e03a52da603be938ff6585fbc9fd8bbff3ba01
  url: https://files.pythonhosted.org/packages/b1/5a/f9316868a836edf6b061e5684fb56edac51344e275a8a6c5b639a6d157ca/trr265-0.0.6.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: The TRR 265 analysis pipeline.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
  run:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
test:
  imports:
  - trr265
