package:
  name: trr265
  version: 0.0.7
source:
  sha256: a7c8b4f1302e40076adc0621356b59f600bac87300ec56e303812864ecce2cd6
  url: https://files.pythonhosted.org/packages/f7/b2/38ed03a47fabb1b79eb6f0a632041032e0c584e147516531a98e25c6e588/trr265-0.0.7.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: The TRR 265 analysis pipeline.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
  run:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
test:
  imports:
  - trr265
