package:
  name: trr265
  version: 0.0.4
source:
  sha256: cab83585449478e13ee230ff47942a8f0ff5c23be499a0afebc88fdbe516a12d
  url: https://files.pythonhosted.org/packages/69/51/b447cf20658d9e1fcc5b63340a9e17371aa32706d78268036b560e541594/trr265-0.0.4.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: The TRR 265 analysis pipeline.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - biur
  - fastcore
  run:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - biur
  - fastcore
test:
  imports:
  - trr265
