package:
  name: trr265
  version: 0.0.2
source:
  sha256: 10e16868374c5e40c4690054f9ef4b02fe16de785477c788a0f219daaffd7a2b
  url: https://files.pythonhosted.org/packages/04/ec/d63b16898426c4844d704d4e965970f79782999ec79f12979d17b8f9dc0a/trr265-0.0.2.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: The TRR 265 analysis pipeline.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  run:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
test:
  imports:
  - trr265
