package:
  name: trr265
  version: 0.0.8
source:
  sha256: 781da8c9f587bd7e0be6f42b4dea8f86893fd1f220c2804631cdd1e3ed193f19
  url: https://files.pythonhosted.org/packages/49/02/238cd540ae9252e4aa0d8232d5242901c20a8764cc7275ebb49314de4702/trr265-0.0.8.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: The TRR 265 analysis pipeline.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
  run:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
test:
  imports:
  - trr265
