package:
  name: trr265
  version: 0.0.9
source:
  sha256: 4a719c8b56aca3bd967b87d13811adf34a491e91bfc7eb90e4214c8cf636d3a2
  url: https://files.pythonhosted.org/packages/16/63/510c82d564bf5a84b0a4932815afcc4fd134a86f716b62a4c5079fdd402b/trr265-0.0.9.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: The TRR 265 analysis pipeline.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
  run:
  - pip
  - python
  - packaging
  - bs4
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - lxml
  - matplotlib
  - seaborn
  - fastcore
test:
  imports:
  - trr265
